idf_component_register(
    SRCS 
        "network_service.c"
        "get_connected/get_connected.c"
    INCLUDE_DIRS 
        "include"
    REQUIRES
        esp_http_client
        esp_wifi
        nvs_flash
        lwip
        esp-wifi-connect
        cjson
    PRIV_REQUIRES
        service_manager
)
